UNDEFINE dbName
UNDEFINE syspw

PROMPT 
PROMPT Especificar el nombre de la base de datos
DEFINE dbName		= &1
PROMPT 
PROMPT Especificar password para usuario SYSTEM
DEFINE syspw     	= &2

--
-- BEGIN
--

-- se mejora los privilegios del usuario CENTRAL
CONNECT system/&&syspw@&&dbName

-- se agregan privilegios extra
-- SELECT privilegios
GRANT SELECT ON clieCENTRAL.PROVEEDOR TO clieCENTRAL;
GRANT SELECT ON clieCENTRAL.PRODUCTO_CENTRAL TO clieCENTRAL;
GRANT SELECT ON clieCENTRAL.FACTURA TO clieCENTRAL;
GRANT SELECT ON clieCENTRAL.AUTO TO clieCENTRAL;
GRANT SELECT ON clieCENTRAL.FACILITA TO clieCENTRAL;
GRANT SELECT ON clieCENTRAL.DETALLE_FACTURA TO clieCENTRAL;
-- INSERT privilegios
GRANT INSERT ON clieCENTRAL.PROVEEDOR TO clieCENTRAL;
GRANT INSERT ON clieCENTRAL.PRODUCTO_CENTRAL TO clieCENTRAL;
GRANT INSERT ON clieCENTRAL.FACTURA TO clieCENTRAL;
GRANT INSERT ON clieCENTRAL.AUTO TO clieCENTRAL;
GRANT INSERT ON clieCENTRAL.FACILITA TO clieCENTRAL;
GRANT INSERT ON clieCENTRAL.DETALLE_FACTURA TO clieCENTRAL;
-- UPDATE privilegios
GRANT UPDATE ON clieCENTRAL.PROVEEDOR TO clieCENTRAL;
GRANT UPDATE ON clieCENTRAL.PRODUCTO_CENTRAL TO clieCENTRAL;
GRANT UPDATE ON clieCENTRAL.FACTURA TO clieCENTRAL;
GRANT UPDATE ON clieCENTRAL.AUTO TO clieCENTRAL;
GRANT UPDATE ON clieCENTRAL.FACILITA TO clieCENTRAL;
GRANT UPDATE ON clieCENTRAL.DETALLE_FACTURA TO clieCENTRAL;
-- DELETE privilegios
GRANT DELETE ON clieCENTRAL.PROVEEDOR TO clieCENTRAL;
GRANT DELETE ON clieCENTRAL.PRODUCTO_CENTRAL TO clieCENTRAL;
GRANT DELETE ON clieCENTRAL.FACTURA TO clieCENTRAL;
GRANT DELETE ON clieCENTRAL.AUTO TO clieCENTRAL;
GRANT DELETE ON clieCENTRAL.FACILITA TO clieCENTRAL;
GRANT DELETE ON clieCENTRAL.DETALLE_FACTURA TO clieCENTRAL;

PROMPT
PROMPT Privilegios avanzados de tablas para clieCENTRAL, agregados con exito
