UNDEFINE dbName
UNDEFINE syspw

PROMPT 
PROMPT Especificar el nombre de la base de datos
DEFINE dbName		= &1
PROMPT 
PROMPT Especificar password para usuario SYSTEM
DEFINE syspw     	= &2

--
-- BEGIN
--

-- se mejora los privilegios del usuario CENTRAL
CONNECT system/&&syspw@&&dbName

-- se agregan privilegios extra
-- SELECT privilegios
GRANT SELECT ON clieGYE.PROVEEDOR TO clieGYE;
GRANT SELECT ON clieGYE.PRODUCTO TO clieGYE;
GRANT SELECT ON clieGYE.PRODUCTO_GYE TO clieGYE;
GRANT SELECT ON clieGYE.CLIENTE_GYE TO clieGYE;
GRANT SELECT ON clieGYE.FACTURA_GYE TO clieGYE;
GRANT SELECT ON clieGYE.AUTO TO clieGYE;
GRANT SELECT ON clieGYE.FACILITA TO clieGYE;
GRANT SELECT ON clieGYE.CLIENTE_AUTO TO clieGYE;
GRANT SELECT ON clieGYE.DETALLE_PROFORMA TO clieGYE;
GRANT SELECT ON clieGYE.DETALLE_FACTURA TO clieGYE;
GRANT SELECT ON clieGYE.PROFORMA_GYE TO clieGYE;
-- INSERT privilegios
GRANT INSERT ON clieGYE.PROVEEDOR TO clieGYE;
GRANT INSERT ON clieGYE.PRODUCTO TO clieGYE;
GRANT INSERT ON clieGYE.PRODUCTO_GYE TO clieGYE;
GRANT INSERT ON clieGYE.CLIENTE_GYE TO clieGYE;
GRANT INSERT ON clieGYE.FACTURA_GYE TO clieGYE;
GRANT INSERT ON clieGYE.AUTO TO clieGYE;
GRANT INSERT ON clieGYE.FACILITA TO clieGYE;
GRANT INSERT ON clieGYE.CLIENTE_AUTO TO clieGYE;
GRANT INSERT ON clieGYE.DETALLE_PROFORMA TO clieGYE;
GRANT INSERT ON clieGYE.DETALLE_FACTURA TO clieGYE;
GRANT INSERT ON clieGYE.PROFORMA_GYE TO clieGYE;
-- UPDATE privilegios
GRANT UPDATE ON clieGYE.PROVEEDOR TO clieGYE;
GRANT UPDATE ON clieGYE.PRODUCTO TO clieGYE;
GRANT UPDATE ON clieGYE.PRODUCTO_GYE TO clieGYE;
GRANT UPDATE ON clieGYE.CLIENTE_GYE TO clieGYE;
GRANT UPDATE ON clieGYE.FACTURA_GYE TO clieGYE;
GRANT UPDATE ON clieGYE.AUTO TO clieGYE;
GRANT UPDATE ON clieGYE.FACILITA TO clieGYE;
GRANT UPDATE ON clieGYE.CLIENTE_AUTO TO clieGYE;
GRANT UPDATE ON clieGYE.DETALLE_PROFORMA TO clieGYE;
GRANT UPDATE ON clieGYE.DETALLE_FACTURA TO clieGYE;
GRANT UPDATE ON clieGYE.PROFORMA_GYE TO clieGYE;
-- DELETE privilegios
GRANT DELETE ON clieGYE.PROVEEDOR TO clieGYE;
GRANT DELETE ON clieGYE.PRODUCTO TO clieGYE;
GRANT DELETE ON clieGYE.PRODUCTO_GYE TO clieGYE;
GRANT DELETE ON clieGYE.CLIENTE_GYE TO clieGYE;
GRANT DELETE ON clieGYE.FACTURA_GYE TO clieGYE;
GRANT DELETE ON clieGYE.AUTO TO clieGYE;
GRANT DELETE ON clieGYE.FACILITA TO clieGYE;
GRANT DELETE ON clieGYE.CLIENTE_AUTO TO clieGYE;
GRANT DELETE ON clieGYE.DETALLE_PROFORMA TO clieGYE;
GRANT DELETE ON clieGYE.DETALLE_FACTURA TO clieGYE;
GRANT DELETE ON clieGYE.PROFORMA_GYE TO clieGYE;

PROMPT
PROMPT Privilegios avanzados de tablas para clieGYE, agregados con exito
