CREATE TABLE proveedor (Ruc NUMBER(13,0) NOT NULL,
                        Nombre VARCHAR2(50) NOT NULL,
                        Direccion VARCHAR2(150) NOT NULL,
                        Telefono NUMBER(10,0) NOT NULL,
                        Email VARCHAR2(100) NOT NULL);
ALTER TABLE proveedor ADD CONSTRAINT proveedor_pk PRIMARY KEY(Ruc);
CREATE MATERIALIZED VIEW LOG ON proveedor;

CREATE TABLE producto (Id NUMBER(20,0) NOT NULL,
                            Costo NUMBER(8,3) NOT NULL,
                            Descripcion VARCHAR2(250),
                            Marca VARCHAR2(20) NOT NULL,
                            Modelo VARCHAR2(30) NOT NULL);
ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY(Id);
CREATE MATERIALIZED VIEW LOG ON producto;

CREATE TABLE auto (Id_Auto NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    Marca VARCHAR2(25) NOT NULL,
                    Modelo VARCHAR2(25) NOT NULL,
                    Cilindraje NUMBER(4,0) NOT NULL,
                    Year DATE NOT NULL,
                    Tipo VARCHAR2(20) NOT NULL);
ALTER TABLE auto ADD CONSTRAINT auto_pk PRIMARY KEY (Id_Auto);
CREATE MATERIALIZED VIEW LOG ON auto;

CREATE TABLE facilita (Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        Id_Producto NUMBER(35) NOT NULL,
                        Id_Proveedor NUMBER(13,0) NOT NULL);
ALTER TABLE facilita ADD CONSTRAINT facilita_pk PRIMARY KEY (Id);
ALTER TABLE facilita ADD CONSTRAINT facilita_fk_prod FOREIGN KEY (Id_Producto) REFERENCES producto (Id);
ALTER TABLE facilita ADD CONSTRAINT facilita_fk_prov FOREIGN KEY (Id_Proveedor) REFERENCES proveedor (Ruc);
CREATE MATERIALIZED VIEW LOG ON facilita;

-- -----------------------------------------------------------------------------------------------------------------

INSERT INTO auto (Id_Auto, Marca,Modelo,Cilindraje,Year,Tipo) VALUES(1, 'Toyota','Hilux',2400,DATE '2007-12-19','Pick Up');
INSERT INTO auto (Id_Auto, Marca,Modelo,Cilindraje,Year,Tipo) VALUES(2, 'Honda','Civic',1800,DATE '2011-07-09','Sedan');
INSERT INTO auto (Id_Auto, Marca,Modelo,Cilindraje,Year,Tipo) VALUES(3, 'Wolkswagen','Golf',1600,DATE '1998-05-14','Hatck Back');
INSERT INTO auto (Id_Auto, Marca,Modelo,Cilindraje,Year,Tipo) VALUES(4, 'Hino','FC-400',3500,DATE '2018-07-25','Mula');

INSERT INTO proveedor VALUES (1721517793001,'Lubtechnology','Juan Tanga Marengo km. 1.5 via Duran',0995407655,'lubtech@lubtech.com');
INSERT INTO proveedor VALUES (1721599993001,'Bretontech','Av. El inca OE-290 y Av. Galo Plaza Lazo',0995444655,'breton@breton.com');
INSERT INTO proveedor VALUES (1551599993001,'Industrias Saga','Av. Republica del Salvador OE-90 y Av. Portugal',0995444125,'saga@saga.com');

INSERT INTO producto VALUES (12345678901234567890,250.501,'Kit embrague Toyota Hilux 2007 4x4','Japan Repuestos','mx375');
INSERT INTO producto VALUES (12345678901233367890,50.50,'Kit frenos Honda Civic 2011','Korean Repuestos','mx300');
INSERT INTO producto VALUES (12345678901777777890,150.80,'Retrovisor Derecho Nissan Centra','Indian Repuestos','mx655');
INSERT INTO producto VALUES (12311118901234567890,25.05,'Agua destilada nacional','Patito','ec777');

INSERT INTO facilita (Id_Producto,Id_Proveedor) VALUES (12345678901234567890,1721517793001);
INSERT INTO facilita (Id_Producto,Id_Proveedor) VALUES (12345678901233367890,1721599993001);
INSERT INTO facilita (Id_Producto,Id_Proveedor) VALUES (12345678901777777890,1551599993001);
INSERT INTO facilita (Id_Producto,Id_Proveedor) VALUES (12311118901234567890,1721599993001);

commit;